---
# tasks file for update_clickhouse_container

- name: "Check running version"
  block:
  - name: "Register running version"
    ansible.builtin.uri:
      url: "http://localhost:8123/?query=SELECT+version%28%29"
      method: GET
      status_code: 200
      return_content: true
      headers:
        X-ClickHouse-User: "{{ _update_clickhouse_container_clickhouse_user }}"
        X-ClickHouse-Key: "{{ _update_clickhouse_container_clickhouse_user_password }}"
    register: _update_clickhouse_container_version_running

  - name: "Assert version running is different that version we wanted upgrade to"
    ansible.builtin.assert:
      that:
        - _update_clickhouse_container_version_running['content'] | trim != _update_clickhouse_container_image_tag
      success_msg: "Different versions, lets go"
      fail_msg: "Same version, nothing to do here"

- name: "Stop a container"
  containers.podman.podman_container:
    name: "{{ _update_clickhouse_container_name }}"
    state: "stopped"

- name: "Rename container"
  ansible.builtin.command: podman rename {{ _update_clickhouse_container_name }} {{ _update_clickhouse_container_name }}-old

- name: "Pull {{ _update_clickhouse_container_image + ':' + _update_clickhouse_container_image_tag }}"
  containers.podman.podman_image:
    name: "{{ _update_clickhouse_container_registry + \"/\" + _update_clickhouse_container_image }}"
    tag: "{{ _update_clickhouse_container_image_tag }}"

- name: Create new version container
  containers.podman.podman_container:
    name: "{{ _update_clickhouse_container_name }}"
    image: "{{ _update_clickhouse_container_image + \":\" + _update_clickhouse_container_image_tag }}"
    state: started
    restart_policy: always
    ulimit:
      - nofile=262144:262144
    env:
      CLICKHOUSE_USER: "{{ _update_clickhouse_container_clickhouse_user }}"
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: "{{ _update_clickhouse_container_clickhouse_user_password }}"
    network:
      - "{{ _update_clickhouse_container_network }}"
    volume:
      - "{{ _update_clickhouse_container_local_path_volume_clickhouse + \":/var/lib/clickhouse:Z\"}}"
      - "{{ _update_clickhouse_container_local_path_volume_clickhouse_logs + \":/var/log/clickhouse-server:Z\" }}"
      - "{{ _update_clickhouse_container_local_path_volume_clickhouse_initialization_scripts + \":/docker-entrypoint-initdb.d:Z\"}}"
      - "{{ _update_clickhouse_container_local_path_volume_clickhouse_config + \":/etc/clickhouse-server/config.d:Z\" }}"

- name: "Workaround to evict ansible call the api before the app is up and running"
  ansible.builtin.pause:
    seconds: 30

- name: "Wait to api be ready"
  block:
  - name: "Register app status"
    ansible.builtin.uri:
      url: "http://localhost:8123"
      method: GET
      status_code: 200
      return_content: true
    register: _update_clickhouse_container_api_ready

- name: "Check running version"
  block:
  - name: "Register running version"
    ansible.builtin.uri:
      url: "http://localhost:8123/?query=SELECT+version%28%29"
      method: GET
      status_code: 200
      return_content: true
      headers:
        X-ClickHouse-User: "{{ _update_clickhouse_container_clickhouse_user }}"
        X-ClickHouse-Key: "{{ _update_clickhouse_container_clickhouse_user_password }}"
    register: _update_clickhouse_container_version_running

- debug:
    var: _update_clickhouse_container_version_running['content']

- name: remove container
  containers.podman.podman_container:
    name: "{{ _update_clickhouse_container_name }}-old"
    state: absent
...
